### ISSUE TITLE
testing results

### ISSUE THREAD

**Issue by feixue94** [vislearn/LessMore#22]
Hi eric, 
thank you for your code.
recently, I reimplment the training process using pytorch.
I find that the model  trained by pytorch without depth performs much worse on the testing sequences of 7Scenes dataset (median error 20degs, 0.5m) than on the training sequences (median 1deg, 0.02m). more details are as follows:
1. the first stage training (using constant depth 3 for 7scenes) can output very accurate results on training sequences but poor results on testing results
2. we use the OpenCV::solvePnPRansac() with flag=SOLVEPNP_P3P to calculate camera poses from predicted coordinates

**Comment by ebrach** [comment]
Hi,

hard to tell what goes wrong with a custom re-implementation, but I assume that the pose estimation (your point 2) is fine, since you get good results on the training set. 

For the first training stage, did you follow the description in the paper, particularly regarding sub-sampling of the training set (-iSS parameter if I remember correctly) and early stopping? Maybe you were training too long, and it overfitted. 

Did you test it for more than one scene?

Recently, I described a more stable procedure for training without a 3D model in this arXiv paper: 
https://arxiv.org/pdf/2002.12324.pdf
This version would not require subsampling or early stopping. I hope to put the corresponding code (also PyTorch based) online soon, but it will likely take a few more weeks. 

Best,
Eric

**Comment by ebrach** [comment]
PS: If you have doubts about the pose estimation part of your implementation, you can cross-check with the ESAC code (https://github.com/vislearn/esac). It is a version of DSAC++ for ensembles of scene coordinate regression networks. If you set the number of networks to 1, this is basically a PyTorch version of DSAC++. However, the ESAC code does not support training without a 3D model.

**Comment by feixue94** [comment]
Hi Eric,
Great thanks. 
I tried on heads, chess, fire and office. But all received poor testing performances.
During the training process, the model was evaluated after each epoch but never achieved promising results. It seems like there is something wrong in my implementation.

I will check my code and find more details from your paper & code.
Thanks again.

Bets,
Fei

**Comment by AzizaZhanabatyrova** [comment]
Hi. For the second and third step of the training do we need to also reduce the number of iterations to avoid overfitting? Or is it not necessary?

**Comment by ebrach** [comment]
Hi. No, that should not be necessary. The standard settings for the number of iterations should be fine. Still, I strongly advice to try the successor of DSAC++: DSAC* which is more stable and also easier to use: https://github.com/vislearn/dsacstar

Depending on your use case, you might also want to take a look at ACE - the successor of DSAC*: https://github.com/nianticlabs/ace (ACE only support training from RGB images, while DSAC* supports training from RGB-D images or 3D models as well).

Best,
Eric
